"use client";

interface ExplanationCardProps {
  topic: string;
  explanation: string;
  isLoading: boolean;
  error: string | null;
}

function LoadingState() {
  return (
    <div className="flex flex-col items-center justify-center py-12 gap-6">
      <div className="flex items-center gap-2">
        {[0, 1, 2].map((i) => (
          <span
            key={i}
            className="loading-dot inline-block h-3 w-3 rounded-full bg-amber-400"
            style={{ animationDelay: `${i * 0.2}s` }}
          />
        ))}
      </div>
      <div className="text-center">
        <p className="font-body text-sm font-medium text-[rgba(15,14,13,0.5)]">
          Generating explanation…
        </p>
        <p className="font-body text-xs text-[rgba(15,14,13,0.3)] mt-1">
          This usually takes a few seconds
        </p>
      </div>
    </div>
  );
}

export default function ExplanationCard({
  topic,
  explanation,
  isLoading,
  error,
}: ExplanationCardProps) {
  // Nothing to show yet
  if (!isLoading && !explanation && !error) return null;

  return (
    <div className="card-elevated rounded-3xl p-7 animate-fade-up w-full">
      {isLoading && <LoadingState />}

      {error && !isLoading && (
        <div className="flex items-start gap-3">
          <div className="mt-0.5 flex-shrink-0 rounded-full bg-red-50 p-2">
            <svg className="h-4 w-4 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
          </div>
          <div>
            <p className="font-body font-semibold text-red-700 text-sm mb-0.5">Something went wrong</p>
            <p className="font-body text-sm text-red-600">{error}</p>
          </div>
        </div>
      )}

      {explanation && !isLoading && (
        <div>
          {/* Topic header */}
          <div className="flex items-start justify-between gap-4 mb-5">
            <div>
              <p className="font-body text-xs font-semibold uppercase tracking-widest text-[rgba(15,14,13,0.4)] mb-1">
                Topic
              </p>
              <h2 className="font-display text-2xl font-bold text-ink leading-tight">
                {topic}
              </h2>
            </div>
            <div className="flex-shrink-0 rounded-2xl bg-amber-50 border border-amber-100 p-3">
              <svg className="h-5 w-5 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" />
              </svg>
            </div>
          </div>

          {/* Divider */}
          <div className="h-px w-full bg-gradient-to-r from-amber-200 via-sage/30 to-transparent mb-5" />

          {/* Explanation text */}
          <div className="explanation-text font-body text-[rgba(15,14,13,0.85)]">
            {explanation.split("\n\n").map((para, i) => (
              para.trim() && (
                <p key={i} className="mb-4 last:mb-0 leading-relaxed">
                  {para.trim()}
                </p>
              )
            ))}
          </div>

          {/* Footer badge */}
          <div className="mt-6 pt-4 border-t border-[rgba(15,14,13,0.06)] flex items-center gap-2">
            <span className="inline-flex items-center gap-1.5 text-xs font-body font-medium text-[rgba(15,14,13,0.4)]">
              <svg className="h-3.5 w-3.5 text-sage" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
              </svg>
              Generated by Gemini AI · Student-friendly summary
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
